Changed to use image v1.15.0
Cray-HPE/hms-bss-charts pull request #6
Opened 2022-01-08 01:38 UTC by shunr-hpe

Jira: CASMHMS-4903

## Summary and Scope

Adopts the BSS change that supports returning Referral Tokens, a UUID.

## Issues and Related PRs

* Resolves CASMHMS-4903
* Merge after https://github.com/Cray-HPE/hms-bss/pull/43
## Testing

see https://github.com/Cray-HPE/hms-bss/pull/43

## Risks and Mitigations

see https://github.com/Cray-HPE/hms-bss/pull/43

## Pull Request Checklist

- [x] Version number(s) incremented, if applicable
- [x] Copyrights updated
- [x] License file intact
- [x] Target branch correct
- [x] CHANGELOG.md updated
- [x] Testing is appropriate and complete, if applicable

2022-01-18 22:09 UTC, nieuwsma requested changes
Why does this folder still exist? https://github.com/Cray-HPE/hms-bss/tree/master/kubernetes/cray-hms-bss

2022-01-19 17:26 UTC, shunr-hpe commented
> Why does this folder still exist? https://github.com/Cray-HPE/hms-bss/tree/master/kubernetes/cray-hms-bss

I think a PR from Sean pulled it back in last year. I'll remove it.

2022-01-20 17:07 UTC, schooler-hpe approved these changes

2022-03-07 21:07 UTC, nieuwsma approved these changes

2022-03-07 21:07 UTC, merged